// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhDJPb4E8G-NwSsO1KNFxLH5mEQnmA9E',
    appId: '1:882373163395:web:918c98a43e53fb32891eb6',
    messagingSenderId: '882373163395',
    projectId: 'sosapp-96931',
    authDomain: 'sosapp-96931.firebaseapp.com',
    storageBucket: 'sosapp-96931.firebasestorage.app',
    measurementId: 'G-46RY0Q0J8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHlMHcVsQTuugB9sO-MJlzZAeeHXUd_0',
    appId: '1:882373163395:android:e0ba442e0bb23a12891eb6',
    messagingSenderId: '882373163395',
    projectId: 'sosapp-96931',
    storageBucket: 'sosapp-96931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkdqkBkwkkMn2QWu4T0vGFdvDPD27mRM',
    appId: '1:882373163395:ios:579a44a54d342766891eb6',
    messagingSenderId: '882373163395',
    projectId: 'sosapp-96931',
    storageBucket: 'sosapp-96931.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCkdqkBkwkkMn2QWu4T0vGFdvDPD27mRM',
    appId: '1:882373163395:ios:579a44a54d342766891eb6',
    messagingSenderId: '882373163395',
    projectId: 'sosapp-96931',
    storageBucket: 'sosapp-96931.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhDJPb4E8G-NwSsO1KNFxLH5mEQnmA9E',
    appId: '1:882373163395:web:92bcc44d114364d8891eb6',
    messagingSenderId: '882373163395',
    projectId: 'sosapp-96931',
    authDomain: 'sosapp-96931.firebaseapp.com',
    storageBucket: 'sosapp-96931.firebasestorage.app',
    measurementId: 'G-E9Q9E1D3KF',
  );
}
